=== Reiex/Endless-History/maps/entites_quetes/dtd/maps.dtd
<!-- DTD Permettant de faire un dossier XML qui signale toutes les entites faisant partit d'une quête -->

<!-- Arbre de base -->

<!ELEMENT entites (monstres, pnjs, meubles, places)>
<!ELEMENT monstres (monstre*)>
<!ELEMENT pnjs (pnj*)>
<!ELEMENT meubles (meuble*)>
<!ELEMENT places (place*)>

<!-- Monstre -->

<!ELEMENT monstre (quete+)>
<!ATTLIST monstre x CDATA #REQUIRED>
<!ATTLIST monstre y CDATA #REQUIRED>
<!ATTLIST monstre type CDATA #REQUIRED>

<!-- PNJ -->

<!ELEMENT pnj (quete+)>
<!ATTLIST pnj x CDATA #REQUIRED>
<!ATTLIST pnj y CDATA #REQUIRED>
<!ATTLIST pnj type CDATA #REQUIRED>

<!-- Meuble -->

<!ELEMENT meuble (quete+)>
<!ATTLIST meuble x CDATA #REQUIRED>
<!ATTLIST meuble y CDATA #REQUIRED>
<!ATTLIST meuble type CDATA #REQUIRED>

<!-- Place -->

<!ELEMENT place (quete+)>
<!ATTLIST place x CDATA #REQUIRED>
<!ATTLIST place y CDATA #REQUIRED>
<!ATTLIST place w CDATA #REQUIRED>
<!ATTLIST place h CDATA #REQUIRED>

<!-- Balises permettant de décrire une entite -->

<!ELEMENT quete EMPTY>
<!ATTLIST quete quete CDATA #REQUIRED>
<!ATTLIST quete histoire CDATA #REQUIRED>

=== Reiex/Endless-History/maps/entites_quetes/maison-1-1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE entites SYSTEM "dtd/maps.dtd">

<entites>
    <monstres/>
    <pnjs/>
    <meubles>
        <meuble x="384" y="64" type="7">
            <quete quete="0" histoire="2"/>
        </meuble>
        <meuble x="320" y="128" type="0">
            <quete quete="2" histoire="2"/>
        </meuble>
    </meubles>
    <places/>
</entites>

=== Reiex/Endless-History/maps/entites_quetes/maison-2-1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE entites SYSTEM "dtd/maps.dtd">

<entites>
    <monstres/>
    <pnjs>
        <pnj x="384" y="64" type="0">
            <quete quete="0" histoire="6"/>
            <quete quete="4" histoire="6"/>
            <quete quete="10" histoire="6"/>
        </pnj>
    </pnjs>
    <meubles/>
    <places/>
</entites>

=== Reiex/Endless-History/maps/entites_quetes/main-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE entites SYSTEM "dtd/maps.dtd">

<entites>
    <monstres>
        <monstre x="4096" y="896" type="1">
            <quete quete="2" histoire="1"/>
        </monstre>
        <monstre x="448" y="5696" type="2">
            <quete quete="13" histoire="3"/>
        </monstre>
        <monstre x="2624" y="1152" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="3328" y="1088" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2048" y="1344" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="3008" y="1472" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2368" y="1728" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2880" y="1984" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="3328" y="1984" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="1856" y="2048" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2304" y="2176" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="3008" y="2496" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="1856" y="2560" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2368" y="2752" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2816" y="3136" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="3264" y="3264" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2240" y="3456" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="3200" y="3776" type="1">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
        <monstre x="2624" y="3840" type="0">
            <quete quete="2" histoire="3"/>
            <quete quete="3" histoire="3"/>
            <quete quete="4" histoire="3"/>
            <quete quete="5" histoire="3"/>
            <quete quete="6" histoire="3"/>
            <quete quete="7" histoire="3"/>
            <quete quete="8" histoire="3"/>
            <quete quete="9" histoire="3"/>
            <quete quete="10" histoire="3"/>
            <quete quete="11" histoire="3"/>
        </monstre>
    </monstres>
    <pnjs/>
    <meubles/>
    <places>
        <place x="12224" y="6144" w="64" h="64">
            <quete quete="0" histoire="0"/>
        </place>
        <place x="12160" y="4864" w="512" h="64">
            <quete quete="1" histoire="0"/>
        </place>
        <place x="12224" y="4608" w="64" h="64">
            <quete quete="3" histoire="0"/>
        </place>
        <place x="256" y="256" w="64" h="128">
            <quete quete="4" histoire="0"/>
        </place>
        <place x="4608" y="2304" w="384" h="384">
            <quete quete="1" histoire="1"/>
        </place>
        <place x="1664" y="896" w="64" h="64">
            <quete quete="1" histoire="3"/>
        </place>
    </places>
</entites>

=== Reiex/Endless-History/maps/entites_quetes/caverne-2-0-1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE entites SYSTEM "dtd/maps.dtd">

<entites>
    <monstres/>
    <pnjs/>
    <meubles>
        <meuble x="640" y="448" type="4">
            <quete quete="2" histoire="5"/>
        </meuble>
    </meubles>
    <places>
        <place x="640" y="896" w="64" h="64">
            <quete quete="1" histoire="5"/>
        </place>
    </places>
</entites>

=== Reiex/Endless-History/maps/entites_quetes/main-3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE entites SYSTEM "dtd/maps.dtd">

<entites>
    <monstres/>
    <pnjs>
        <pnj x="5952" y="64" type="3">
            <quete quete="34" histoire="0"/>
        </pnj>
    </pnjs>
    <meubles/>
    <places>
        <place x="192" y="12672" w="64" h="64">
            <quete quete="27" histoire="0"/>
        </place>
        <place x="5824" y="7680" w="64" h="64">
            <quete quete="28" histoire="0"/>
        </place>
        <place x="2944" y="7104" w="640" h="576">
            <quete quete="30" histoire="0"/>
        </place>
        <place x="1152" y="256" w="256" h="384">
            <quete quete="31" histoire="0"/>
        </place>
        <place x="5056" y="576" w="64" h="64">
            <quete quete="32" histoire="0"/>
        </place>
        <place x="5760" y="64" w="448" h="256">
            <quete quete="33" histoire="0"/>
        </place>
        <place x="1344" y="384" w="64" h="64">
            <quete quete="7" histoire="8"/>
        </place>
        <place x="4224" y="4416" w="64" h="64">
            <quete quete="6" histoire="7"/>
        </place>
    </places>
</entites>
