=== Reiex/Endless-History/maps/quetes/dtd/quetes.dtd
<!-- DTD Permettant de faire un dossier XML qui représente une quête -->

<!-- Arbre de base -->

<!ELEMENT actions ( (deplacement | attaque_base | mort | immobilisation | dialogue | donner_objet | detruire | final)* )>


<!-- ACTIONS A DECLENCHER -->


<!-- Déplacement -->

<!ELEMENT deplacement EMPTY>
<!ATTLIST deplacement x (-2 | -1 | 0 | 1 | 2) #REQUIRED>
<!ATTLIST deplacement y (-2 | -1 | 0 | 1 | 2) #REQUIRED>
<!ATTLIST deplacement joueur (True | False) #REQUIRED>


<!-- Attaque de base -->

<!ELEMENT attaque_base EMPTY>
<!ATTLIST attaque_base vitesse CDATA #REQUIRED>
<!ATTLIST attaque_base joueur (True | False) #REQUIRED>


<!-- Mort -->

<!ELEMENT mort EMPTY>
<!ATTLIST mort joueur (True | False) #REQUIRED>


<!-- Immoblisation -->

<!ELEMENT immobilisation EMPTY>
<!ATTLIST immobilisation vitesse CDATA #REQUIRED>
<!ATTLIST immobilisation joueur (True | False) #REQUIRED>


<!-- Dialogue -->

<!ELEMENT dialogue (#PCDATA)>
<!ATTLIST dialogue joueur (True | False) #REQUIRED>


<!-- Donner un objet au joueur -->

<!ELEMENT donner_objet EMPTY>
<!ATTLIST donner_objet type CDATA #REQUIRED>


<!-- Destruction -->

<!ELEMENT detruire EMPTY>


<!-- Quête finale -->

<!ELEMENT final EMPTY>

=== Reiex/Endless-History/maps/quetes/0-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Bonjour ! ...
Excusez-moi mais.. Où suis-je ?</dialogue>
    <dialogue joueur="False">Dans ma maison.</dialogue>
    <dialogue joueur="True">Oui je sais, mais vous pourriez
être plus précis ?</dialogue>
    <dialogue joueur="False">Et bien vous vous trouvez sur la
route entre la grande mine et Aubaric.</dialogue>
    <dialogue joueur="True">Aubaric ? C'est quoi ?</dialogue>
    <dialogue joueur="False">Vous devez venir de loin...
C'est tout simplement le centre de Faymont, la région dans
laquelle vous vous trouvez.</dialogue>
    <dialogue joueur="True">Et c'est où ?</dialogue>
    <dialogue joueur="False">Au nord ouest d'ici, pas très loin.</dialogue>
    <dialogue joueur="True">Merci !</dialogue>
    <dialogue joueur="False">Et faites attention aux monstres !
Depuis peu ces horreurs ont envahi toute la region...</dialogue>
    <dialogue joueur="True">Et vous savez d'où ils viennent ?</dialogue>
    <dialogue joueur="False">Non... Mais faites attention !
Et prenez cette potion au cas où il vous arriverait malheur.</dialogue>
    <donner_objet type="5"/>
    <dialogue joueur="True">Merci beaucoup !</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/6-4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="False">Alors ?</dialogue>
    <dialogue joueur="True">Les chemins qui mènent vers la
zone sécurisée sont gardés et il est impossible de passer.</dialogue>
    <dialogue joueur="False">Ah... Je vais quand même vous
dédommager pour votre aide.</dialogue>
    <donner_objet type="6"/>
    <dialogue joueur="False">Et puisque vous ne semblez pas
avoir de problème avec les monstres...</dialogue>
    <dialogue joueur="False">Est ce que vous pourriez me
débarasser des quelques uns qui trainent autour de ma maison
s'il vous plaît ?</dialogue>
    <dialogue joueur="True">Pas de problème.</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/4-9.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Voilà, j'ai tué les quelques monstres qui traînaient</dialogue>
    <dialogue joueur="False">Merveilleux ! Voici pour vous récompenser.</dialogue>
    <donner_objet type="11"/>
    <dialogue joueur="False">Et...</dialogue>
    <dialogue joueur="True">Oui ?</dialogue>
    <dialogue joueur="False">Il reste un de ces monstres qui s'est
caché dans une grotte au nord du lac.</dialogue>
    <dialogue joueur="False">Pourriez-vous vous en occuper ?</dialogue>
    <dialogue joueur="True">J'y vais de ce pas.</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/8-5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <deplacement x="1" y="0" joueur="True"/>

    <deplacement x="0" y="-2" joueur="True"/>

    <dialogue joueur="True">Une lettre est posée sur cette table:</dialogue>
    <dialogue joueur="True">"Ces abominations sont de plus en plus nombreuses.</dialogue>
    <dialogue joueur="True">Et leurs attaques sont de plus en plus coordonnées.</dialogue>
    <dialogue joueur="True">Pendant plusieurs jours, aucune n'apparaît...
puis d'un coup, elles sortent en groupes.</dialogue>
    <dialogue joueur="True">De la rivière, des montagnes, de la grotte,
elles arrivent toutes en même temps.</dialogue>
    <dialogue joueur="True">J'ai commencé à creuser un tunnel, pour m'échapper.</dialogue>
    <dialogue joueur="True">Mais cela prend du temps, et je dois tenir bon...
me défendre.</dialogue>
    <dialogue joueur="True">Cependant, si je ne suis pas assez rapide, je
ne serai bientot plus de taille à lutter."</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-34.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>

    <dialogue joueur="True">Bonjour ! C'est bien par là Capires ?</dialogue>
    <dialogue joueur="False">Oui. C'est bien là.</dialogue>
    <dialogue joueur="False">Mais la route est barrée.</dialogue>
    <dialogue joueur="True">Je peux passer ?</dialogue>
    <dialogue joueur="False">Non. Il faut d'abord nous prouver que vous
êtes capable de vous rendre utile.</dialogue>
    <dialogue joueur="False">Allez tuer quelques monstres et revenez
nous voir.</dialogue>
    <dialogue joueur="True">...</dialogue>
    <dialogue joueur="True">...</dialogue>
    <dialogue joueur="True">Non.</dialogue>
    <dialogue joueur="True">J'en ai marre de ces quêtes à la con.
C'est humiliant !</dialogue>
    <dialogue joueur="True">Déjà que ma vie se résume à se faire
controler par quelques touches sur un clavier !</dialogue>
    <dialogue joueur="True">Je devrais au moins avoir le droit à une histoire
descente où des vraies quêtes. Pas ces vulgaires quêtes de
remplissage !</dialogue>
    <dialogue joueur="True">...</dialogue>
    <dialogue joueur="True">J'en ai marre.</dialogue>

    <final/>

    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>

    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>

</actions>

=== Reiex/Endless-History/maps/quetes/2-4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">M.Hepsus. Je présume...</dialogue>
    <dialogue joueur="False">Oui ?</dialogue>
    <dialogue joueur="True">Il semblerait que vous ayez laissé un tas d'os,
dans la maison d'un de vos voisins.. Il semblerait même
que ces os soient ceux du voisin.</dialogue>
    <dialogue joueur="False">Vous avez une preuve ?</dialogue>
    <dialogue joueur="True">Non mais le conseil de la ville
serait très intéressé de voir la lettre qu'il comptait vous envoyer...</dialogue>
    <immobilisation vitesse="250" joueur="True"/>
    <deplacement x="0" y="-1" joueur="False"/>
    <deplacement x="1" y="0" joueur="False"/>
    <deplacement x="1" y="0" joueur="False"/>
    <deplacement x="1" y="0" joueur="False"/>
    <deplacement x="1" y="0" joueur="False"/>
    <deplacement x="1" y="0" joueur="False"/>
    <deplacement x="1" y="0" joueur="False"/>
    <deplacement x="0" y="-1" joueur="False"/>
    <detruire/>
    <dialogue joueur="True">Fuir ne sert pas à grand chose dans une maison
avec une seule sortie..</dialogue>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
</actions>

=== Reiex/Endless-History/maps/quetes/0-29.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="False">Bonjour ! Que me voulez vous ?</dialogue>
    <dialogue joueur="True">Bonjour, sous pourriez m'indiquer
la ville la plus proche s'il vous plaît ?</dialogue>
    <dialogue joueur="True">Je cherche à comprendre cette invasion de
monstres et à aider à vous en débarrasser si possible...</dialogue>
    <dialogue joueur="False">Et bien... il y a Capires, au nord.</dialogue>
    <dialogue joueur="False">Elle a plutôt bien resisté, vous pourrez
surement trouver quelqu'un qui sait ce qui s'est passé.</dialogue>
    <dialogue joueur="True">Merci ! Vous n'auriez aucune
information sur ces monstres par hasard ?</dialogue>
    <dialogue joueur="False">Non. Pour tout dire les monstres
ne s'aventurent que très rarement dans les parages...</dialogue>
    <dialogue joueur="True">Vous vivez en dehors de la zone protégée pourtant...</dialogue>
    <dialogue joueur="True">Bon. C'est pas grave, merci quand même !</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-15.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <dialogue joueur="True">C'est parti...</dialogue>
    <dialogue joueur="True">Je suppose que l'aventure commence réellement
maintenant.</dialogue>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <dialogue joueur="True">Je suis un peu déçu quand même...</dialogue>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <dialogue joueur="True">Ce jeu m'a pas l'air passionnant.</dialogue>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <dialogue joueur="True">Bon, j'ai plus qu'a trouve un passage
à travers ces montagnes...</dialogue>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

</actions>
