=== Reiex/Endless-History/maps/quetes/dtd/quetes.dtd
<!-- DTD Permettant de faire un dossier XML qui représente une quête -->

<!-- Arbre de base -->

<!ELEMENT actions ( (deplacement | attaque_base | mort | immobilisation | dialogue | donner_objet | detruire | final)* )>


<!-- ACTIONS A DECLENCHER -->


<!-- Déplacement -->

<!ELEMENT deplacement EMPTY>
<!ATTLIST deplacement x (-2 | -1 | 0 | 1 | 2) #REQUIRED>
<!ATTLIST deplacement y (-2 | -1 | 0 | 1 | 2) #REQUIRED>
<!ATTLIST deplacement joueur (True | False) #REQUIRED>


<!-- Attaque de base -->

<!ELEMENT attaque_base EMPTY>
<!ATTLIST attaque_base vitesse CDATA #REQUIRED>
<!ATTLIST attaque_base joueur (True | False) #REQUIRED>


<!-- Mort -->

<!ELEMENT mort EMPTY>
<!ATTLIST mort joueur (True | False) #REQUIRED>


<!-- Immoblisation -->

<!ELEMENT immobilisation EMPTY>
<!ATTLIST immobilisation vitesse CDATA #REQUIRED>
<!ATTLIST immobilisation joueur (True | False) #REQUIRED>


<!-- Dialogue -->

<!ELEMENT dialogue (#PCDATA)>
<!ATTLIST dialogue joueur (True | False) #REQUIRED>


<!-- Donner un objet au joueur -->

<!ELEMENT donner_objet EMPTY>
<!ATTLIST donner_objet type CDATA #REQUIRED>


<!-- Destruction -->

<!ELEMENT detruire EMPTY>


<!-- Quête finale -->

<!ELEMENT final EMPTY>

=== Reiex/Endless-History/maps/quetes/8-4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <dialogue joueur="True">"C'est un trou de verdure où chante une rivière,</dialogue>

    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>

    <dialogue joueur="True">accrochant follement aux herbes des haillons d'argent;</dialogue>

    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>

    <deplacement x="0" y="-1" joueur="True"/>

    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>
    <deplacement x="-1" y="0" joueur="True"/>

    <dialogue joueur="True">où le soleil, de la montagne fière, luit:</dialogue>

    <deplacement x="1" y="0" joueur="True"/>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <dialogue joueur="True">c'est un petit val qui mousse de rayons.</dialogue>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>

    <deplacement x="0" y="-2" joueur="True"/>

    <dialogue joueur="True">Un soldat jeune, bouche ouverte, tête nue,
et la nuque baignant dans le frais cresson bleu, dort;</dialogue>
    <dialogue joueur="True">il est étendu dans l'herbe, sous la nue,
pâle dans son lit vert où la lumière pleut.</dialogue>

    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>

    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>
    <deplacement x="1" y="0" joueur="True"/>

    <deplacement x="0" y="-1" joueur="True"/>

    <deplacement x="1" y="0" joueur="True"/>

    <deplacement x="0" y="2" joueur="True"/>

    <dialogue joueur="True">Les pieds dans les glaïeuls, il dort.</dialogue>
    <dialogue joueur="True">Souriant comme sourirait un enfant malade,
il fait un somme:</dialogue>
    <dialogue joueur="True">Nature, berce-le chaudement : il a froid.</dialogue>

    <deplacement x="-1" y="0" joueur="True"/>

    <deplacement x="0" y="1" joueur="True"/>
    <deplacement x="0" y="1" joueur="True"/>

    <deplacement x="1" y="0" joueur="True"/>

    <deplacement x="0" y="-2" joueur="True"/>

    <dialogue joueur="True">Les parfums ne font pas frissonner sa narine;</dialogue>
    <dialogue joueur="True">Il dort dans le soleil,
la main sur sa poitrine, Tranquille.</dialogue>
    <dialogue joueur="True">Il a...</dialogue>
    <dialogue joueur="True">deux trous rouges...</dialogue>
    <dialogue joueur="True">au côté droit."</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Bonjour !</dialogue>
    <dialogue joueur="True">Je m'appelle Reiex et comme tu peux le voir,
je suis un héros de jeu vidéo !</dialogue>
    <dialogue joueur="True">J'ai été créé il y a quelques temps au fond
d'une caverne avec un clavier qui peux lancer des sorts !</dialogue>
    <dialogue joueur="True">Enfin... pouvait...
il pouvait lancer des sorts....</dialogue>
    <dialogue joueur="True">Je viens d'en sortir et... apparemment...
il ne fonctionne plus. Ahah !</dialogue>
    <dialogue joueur="True">Comme il n'est pas question que je m'en
débarasse et qu'il faut bien que je me défende, j'ai donc décidé
de m'en servir... d'une autre manière</dialogue>
    <dialogue joueur="True">Maintenant je suppose que tu veux
savoir comment me déplacer ?</dialogue>
    <dialogue joueur="True">Et bien c'est grâce aux touches Z, Q, S et D.</dialogue>
    <dialogue joueur="True">Pour attaquer, il suffit de cliquer dans
la bonne direction.</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/1-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="False">Bonjour !
Vous voulez un lit pour la nuit ?</dialogue>
    <dialogue joueur="True">Non.</dialogue>
    <dialogue joueur="False">Ah je sais, depuis que ces monstres
occupent la région, personne ne vient plus dormir ici.</dialogue>
    <dialogue joueur="False">En fait c'est surtout l'un
d'eux qui pose problème.</dialogue>
    <dialogue joueur="False">Il doit avoir une forme d'intelligence
car il se cache dans un bosquet un peu à l'ouest
et terrorise tout les voyageurs qui passent sur le
chemin entre ici et Aubaric.</dialogue>
    <dialogue joueur="True">Si vous voulez, je peux vous en débarasser.</dialogue>
    <dialogue joueur="False">Ce serait merveilleux !
Mais restez prudent...</dialogue>
</actions>
