=== Reiex/Endless-History/maps/quetes/dtd/quetes.dtd
<!-- DTD Permettant de faire un dossier XML qui représente une quête -->

<!-- Arbre de base -->

<!ELEMENT actions ( (deplacement | attaque_base | mort | immobilisation | dialogue | donner_objet | detruire | final)* )>


<!-- ACTIONS A DECLENCHER -->


<!-- Déplacement -->

<!ELEMENT deplacement EMPTY>
<!ATTLIST deplacement x (-2 | -1 | 0 | 1 | 2) #REQUIRED>
<!ATTLIST deplacement y (-2 | -1 | 0 | 1 | 2) #REQUIRED>
<!ATTLIST deplacement joueur (True | False) #REQUIRED>


<!-- Attaque de base -->

<!ELEMENT attaque_base EMPTY>
<!ATTLIST attaque_base vitesse CDATA #REQUIRED>
<!ATTLIST attaque_base joueur (True | False) #REQUIRED>


<!-- Mort -->

<!ELEMENT mort EMPTY>
<!ATTLIST mort joueur (True | False) #REQUIRED>


<!-- Immoblisation -->

<!ELEMENT immobilisation EMPTY>
<!ATTLIST immobilisation vitesse CDATA #REQUIRED>
<!ATTLIST immobilisation joueur (True | False) #REQUIRED>


<!-- Dialogue -->

<!ELEMENT dialogue (#PCDATA)>
<!ATTLIST dialogue joueur (True | False) #REQUIRED>


<!-- Donner un objet au joueur -->

<!ELEMENT donner_objet EMPTY>
<!ATTLIST donner_objet type CDATA #REQUIRED>


<!-- Destruction -->

<!ELEMENT detruire EMPTY>


<!-- Quête finale -->

<!ELEMENT final EMPTY>

=== Reiex/Endless-History/maps/quetes/0-12.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Voilà, je vous ai débarrassé de ces monstres
au sud. Maintenant dites-moi d'où viennent ces monstres et comment
aller vers le nord !</dialogue>
    <dialogue joueur="False">Très bien.</dialogue>
    <dialogue joueur="False">Les monstres que vous voyez ont commencé
à apparaître il y a quelques mois environ.</dialogue>
    <dialogue joueur="False">La région de Faymont est une très
grande région composée de 4 villes: Aubaric, Minemart,
Capires, et Fronfay</dialogue>
    <dialogue joueur="False">Aubaric est maintenant la seule ville qui
se trouve dans une zone sécurisée. Enfin à notre connaissance...</dialogue>
    <dialogue joueur="False">Minemart est une grande ville minière un peu
au nord d'ici, c'est elle qui est reliée à Aubaric par la route
principale, mais cette route est maintenant barricadée.</dialogue>
    <dialogue joueur="False">Capires était l'ancienne capitale de Faymont,
une très grande ville qui se trouve derrière les montagnes, au nord-est.</dialogue>
    <dialogue joueur="False">Faymont, enfin, n'était qu'une petite ville
très au nord.</dialogue>
    <dialogue joueur="True">Et ces villes existent encore ?</dialogue>
    <dialogue joueur="False">On ne sait pas. Vous pourrez allez le
voir par vous même.</dialogue>
    <dialogue joueur="False">Il y a un petit chemin vers les montagnes
au nord-est de la ville. Vous pourrez l'emprunter, il y a probablement
moins de monstres dans les montagnes que sur les routes.</dialogue>
    <dialogue joueur="False">Par contre, celui qui garde cette route
vous laissera sortir, mais pas revenir. Assurez vous d'être
prêt avant de partir...</dialogue>
    <dialogue joueur="True">Merci.</dialogue>
    <dialogue joueur="False">Oh ! Et avant de partir.
Voilà de quoi vous remercier pour nous avoir débarrassé de ces monstres.</dialogue>
    <donner_objet type="1"/>
</actions>

=== Reiex/Endless-History/maps/quetes/4-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="False">Bonjour !</dialogue>
    <dialogue joueur="False">Vous voulez bien m'aider ?</dialogue>
    <dialogue joueur="True">... De quoi s'agit-il ?</dialogue>
    <dialogue joueur="False">Et bien... je comptais combattre ces monstres
qui sont arrivés il y a peu.</dialogue>
    <dialogue joueur="False">Mais il semblerais que j'ai oublié mon épée.</dialogue>
    <dialogue joueur="False">Pourriez-vous aller la chercher chez ma fille ?</dialogue>
    <dialogue joueur="False">Elle habite dans la petite maison au nord d'ici.</dialogue>
    <dialogue joueur="True">D'accord.</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-23.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="False">Ah ! Vous vous êtes enfin réveillé !</dialogue>
    <dialogue joueur="True">... Je suis où ? Vous êtes qui ?</dialogue>
    <dialogue joueur="False">Vous êtes dans mon chalet. Il était très
fréquenté par les montagnards avant que les monstres
envahissent la région...</dialogue>
    <dialogue joueur="False">Je vous ai trouvé évanoui en hypothermie
dans le fossé à côté d'ici...</dialogue>
    <dialogue joueur="False">Que faites vous ici ?</dialogue>
    <dialogue joueur="True">J'essaye de trouver un passage vers le nord,
justement pour découvrir d'où viennent ces monstes.</dialogue>
    <dialogue joueur="False">Oui, il y en à un, mais il faut encore
monter un peu...</dialogue>
    <dialogue joueur="False">Ne sortez pas comme ça alors !</dialogue>
    <deplacement x="2" y="0" joueur="False"/>
    <deplacement x="0" y="2" joueur="False"/>
    <dialogue joueur="False">Voici pour vous.</dialogue>
    <donner_objet type="9"/>
    <dialogue joueur="False">Bonne chance !</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/5-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Voyons ce qu'on a là...</dialogue>
    <dialogue joueur="True">Un os... </dialogue>
    <dialogue joueur="True">Un autre os...</dialogue>
    <dialogue joueur="True">Encore un... Je fais pas ça toute la journée hein !
Je commence à en avoir marre de ces quêtes secondaires minables...</dialogue>
    <dialogue joueur="True">Ah ! Une potion de vie ! J'éspère que ça périme pas.</dialogue>
    <donner_objet type="5"/>
    <dialogue joueur="True">Ah ! Encore mieux !</dialogue>
    <donner_objet type="8"/>
</actions>

=== Reiex/Endless-History/maps/quetes/6-0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="False">Oh ! Bonjour !
Je ne vous ai jamais vu dans cette region !</dialogue>
    <dialogue joueur="True">C'est normal, c'est la première
fois que je viens ici.</dialogue>
    <dialogue joueur="False">Comment ça ?</dialogue>
    <dialogue joueur="False">Vous voulez dire que vous avez trouvé
un passage vers le sud ?</dialogue>
    <dialogue joueur="True">Non, pas vraiment... On m'a laissé
venir mais on ne me laissera pas repasser...</dialogue>
    <dialogue joueur="False">Oh...</dialogue>
    <dialogue joueur="False">Depuis que ces monstres ont
envahi la région, elle est devenue invivable.</dialogue>
    <dialogue joueur="False">Mais j'ai toujours vécu ici !
Je ne connais pas de passage pour aller au sud,
dans la zone sécurisée.</dialogue>
    <dialogue joueur="False">Et avec ces monstes, je ne
peux pu partir en chercher sans risques.</dialogue>
    <dialogue joueur="False">Vous qui êtes venu jusqu'ici,
vous pourriez chercher un passage pour moi ?</dialogue>
    <dialogue joueur="True">Je peux toujours essayer.</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-6.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Bonjour, vous êtes bien le chef
de la ville ?</dialogue>
    <dialogue joueur="False">En effet, en quoi puis-je vous
être utile ?</dialogue>
    <dialogue joueur="True">Et bien j'aimerais savoir d'où
viennent ces monstres qui envahissent actuellement la région.</dialogue>
    <dialogue joueur="False">Du nord, mais toutes les routes
sont barricadées, pour la sécurité de la ville et de ses
environs.</dialogue>
    <dialogue joueur="True">Il n'y a vraiment aucun moyen
de passer ?</dialogue>
    <dialogue joueur="False">Non, c'est trop dangereux, même
avec ces barricades il reste des monstres qui trouvent
des passages, et qui envahissent le sud de la ville...</dialogue>
    <dialogue joueur="True">Et si je vous débarassais de
ces monstres au sud, vous m'ouvririez le passage vers le nord ?</dialogue>
    <dialogue joueur="False">Essayez si vous voulez, mais je ne
suis pas responsable de ce qui pourrait vous arriver..</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">C'est bizarre, ces monstres sont les mêmes
que ceux qui étaient dans la caverne...</dialogue>
    <dialogue joueur="True">Cet homme n'a pas l'air d'en savoir
beaucoup sur eux, mais peut être que je trouverais des
infos dans cette ville: "Aubaric".</dialogue>
    <dialogue joueur="True">D'ailleurs je vais t'expliquer
comment utiliser cette potion et regarder la carte.</dialogue>
    <dialogue joueur="True">Pour ouvrir l'inventaire il faut
appuyer sur ESPACE. Tu peux avoir beaucoup d'objets, t'equiper
de certains commes armures, en utiliser d'autres comme consommables,
c'est le cas de la potion.</dialogue>
    <dialogue joueur="True">Deplace la potion dans la case des consommables
en haut à droite, puis referme l'inventaire.</dialogue>
    <dialogue joueur="True">Une fois l'inventaire fermé, tu n'a
plus qu'a faire un clique droit pour utiliser l'objet dans
la case des consommables.</dialogue>
    <dialogue joueur="True">Pour regarder la carte, enfin, il suffit
d'appuyer sur la touche M.</dialogue>
</actions>

=== Reiex/Endless-History/maps/quetes/0-14.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE actions SYSTEM "dtd/quetes.dtd">

<actions>
    <dialogue joueur="True">Bonjour ! Le chef m'a dit que vous
m'autoriseriez à passer.</dialogue>
    <dialogue joueur="False">Oui, en effet, sachez cependant que vous ne
pourrez pas revenir en arrière.</dialogue>
    <dialogue joueur="True">Oui, je sais, merci.</dialogue>
    <deplacement x="-1" y="0" joueur="False"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="0" y="-1" joueur="True"/>
    <deplacement x="1" y="0" joueur="False"/>
</actions>
